import Link from "next/link";
import { MetricCard, YoutubeWorkbenchShell } from "@/components/youtube-workbench-shell";
import { focusVideo, youtubeSummary } from "@/content/youtube-workbench";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("YouTube Workbench — Project 001", "The YouTube operating view for Maple Leaf Edu Travel inside Laicai OS.", "/projects/maple-leaf-edu-travel/youtube");

export default function YoutubeOverview() {
  return <YoutubeWorkbenchShell active="Overview" eyebrow="PROJECT 001 · YOUTUBE WORKBENCH" title="Content performance, turned into the next action." copy="A focused operating view for growing Maple Leaf Edu Travel—not a separate analytics product.">
    <section className="metric-grid"><MetricCard label="Verified stage views" value={youtubeSummary.verifiedViews.toLocaleString()} detail="Across 7 recoverable uploads" accent /><MetricCard label="Published content" value={String(youtubeSummary.publishedVideos)} detail="Current Project 001 library" /><MetricCard label="Detailed snapshots" value={String(youtubeSummary.detailedSnapshots)} detail="Retention data currently verified" /><MetricCard label="Data coverage" value="Partial" detail="Connect Studio for daily updates" /></section>
    <section className="workbench-grid"><article className="dashboard-panel performance-panel"><div className="panel-heading"><div><span>STAGE PERFORMANCE</span><h2>5,306 verified views</h2></div><small>Historical aggregate</small></div><div className="stage-chart" role="img" aria-label="Verified cumulative stage views reaching 5,306"><div className="chart-grid-lines" /><svg viewBox="0 0 720 210" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6d68ff" stopOpacity=".3"/><stop offset="1" stopColor="#6d68ff" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d="M0 190 C90 180 110 166 175 158 S270 135 328 126 S405 90 470 96 S575 58 720 24 L720 210 L0 210Z"/><path className="chart-line" d="M0 190 C90 180 110 166 175 158 S270 135 328 126 S405 90 470 96 S575 58 720 24"/></svg><div className="chart-final">5,306</div></div><div className="chart-axis"><span>First upload</span><span>Latest verified snapshot</span></div></article><article className="dashboard-panel laicai-insight"><div className="insight-badge">L</div><span>LAICAI TODAY</span><h2>The first three seconds are the current bottleneck.</h2><p>{focusVideo.swiped}% swiped away on the best-documented Short. Before increasing posting frequency, test a clearer opening promise and move the strongest China-learning moment into frame one.</p><Link href="/projects/maple-leaf-edu-travel/youtube/retention">Open retention diagnosis →</Link></article></section>
    <section className="workbench-grid lower"><article className="dashboard-panel focus-video"><div className="panel-heading"><div><span>CURRENT FOCUS VIDEO</span><h2>{focusVideo.title}</h2></div><b className="status-warning">{focusVideo.status}</b></div><div className="focus-stats"><div><span>Views</span><strong>{focusVideo.views.toLocaleString()}</strong></div><div><span>Average watch</span><strong>{focusVideo.averageWatch}</strong></div><div><span>Stayed to watch</span><strong>{focusVideo.stayed}%</strong></div></div><div className="retention-bar"><i style={{ width: `${focusVideo.stayed}%` }} /><span style={{ left: `${focusVideo.stayed}%` }} /></div><div className="retention-legend"><span><i className="stay"/>Stayed {focusVideo.stayed}%</span><span><i className="swipe"/>Swiped {focusVideo.swiped}%</span></div></article><article className="dashboard-panel quick-paths"><span>GO DEEPER</span><h2>Three views, one learning loop.</h2><Link href="/projects/maple-leaf-edu-travel/youtube/videos"><b>Videos</b><small>Compare every published asset</small><em>→</em></Link><Link href="/projects/maple-leaf-edu-travel/youtube/daily"><b>Daily</b><small>Read momentum after publishing</small><em>→</em></Link><Link href="/projects/maple-leaf-edu-travel/youtube/retention"><b>Retention</b><small>Find when viewers leave</small><em>→</em></Link></article></section>
    <p className="data-footnote">Verified data only. Blank metrics are intentionally not estimated; connect YouTube Studio or import daily exports to complete the workbench.</p>
  </YoutubeWorkbenchShell>;
}
