import Link from "next/link";
import { MetricCard, YoutubeWorkbenchShell } from "@/components/youtube-workbench-shell";
import { dailyViews, focusVideo, periodSummary, youtubeSummary } from "@/content/youtube-workbench";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("YouTube Workbench — Project 001", "The YouTube operating view for MapleLeaf Edu Travel inside Laicai OS.", "/projects/maple-leaf-edu-travel/youtube");

export default function YoutubeOverview() {
  const maxViews = Math.max(...dailyViews.map((day) => day.views));
  const points = dailyViews.map((day, index) => `${(index / (dailyViews.length - 1)) * 720},${190 - (day.views / maxViews) * 160}`).join(" ");

  return <YoutubeWorkbenchShell active="Overview" eyebrow="PROJECT 001 · YOUTUBE WORKBENCH" title="Content performance, turned into the next action." copy="A focused operating view for growing MapleLeaf Edu Travel—not a separate analytics product.">
    <section className="metric-grid"><MetricCard label="Lifetime content views" value={youtubeSummary.verifiedViews.toLocaleString()} detail="Current public content row total" accent /><MetricCard label="Past 28 days" value={periodSummary.views.toLocaleString()} detail={periodSummary.label} /><MetricCard label="Published content" value={String(youtubeSummary.publishedVideos)} detail={`${youtubeSummary.shorts} Shorts · ${youtubeSummary.longVideos} videos`} /><MetricCard label="Subscribers" value={String(youtubeSummary.subscribers)} detail={`+${periodSummary.subscriberChange} in the past 28 days`} /></section>
    <section className="workbench-grid"><article className="dashboard-panel performance-panel"><div className="panel-heading"><div><span>28-DAY PERFORMANCE</span><h2>{periodSummary.views.toLocaleString()} views · {periodSummary.watchHours.toFixed(1)} watch hours</h2></div><small>{periodSummary.label}</small></div><div className="stage-chart" role="img" aria-label="Daily YouTube views from July 13 through August 9, totaling 5,195"><div className="chart-grid-lines" /><svg viewBox="0 0 720 210" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6d68ff" stopOpacity=".3"/><stop offset="1" stopColor="#6d68ff" stopOpacity="0"/></linearGradient></defs><polygon className="chart-area" points={`0,210 ${points} 720,210`} /><polyline className="chart-line" points={points} /></svg><div className="chart-final">Peak 1,544</div></div><div className="chart-axis"><span>Jul 13</span><span>Jul 23</span><span>Jul 31</span><span>Aug 9</span></div></article><article className="dashboard-panel laicai-insight"><div className="insight-badge">L</div><span>LAICAI TODAY</span><h2>The content holds attention; the first-frame promise needs work.</h2><p>The focus Short averages {focusVideo.averageViewed}% viewed after the viewer chooses to watch, but only {focusVideo.stayed}% continued instead of swiping. Improve selection before changing the core story.</p><Link href="/projects/maple-leaf-edu-travel/youtube/retention">Open retention diagnosis →</Link></article></section>
    <section className="workbench-grid lower"><article className="dashboard-panel focus-video"><div className="panel-heading"><div><span>CURRENT FOCUS VIDEO</span><h2>{focusVideo.title}</h2></div><b className="status-warning">{focusVideo.status}</b></div><div className="focus-stats"><div><span>Views</span><strong>{focusVideo.views.toLocaleString()}</strong></div><div><span>Average watch</span><strong>{focusVideo.averageWatch}</strong></div><div><span>Stayed to watch</span><strong>{focusVideo.stayed}%</strong></div></div><div className="retention-bar"><i style={{ width: `${focusVideo.stayed}%` }} /><span style={{ left: `${focusVideo.stayed}%` }} /></div><div className="retention-legend"><span><i className="stay"/>Stayed {focusVideo.stayed}%</span><span><i className="swipe"/>Swiped {focusVideo.swiped}%</span></div></article><article className="dashboard-panel quick-paths"><span>GO DEEPER</span><h2>Three views, one learning loop.</h2><Link href="/projects/maple-leaf-edu-travel/youtube/videos"><b>Videos</b><small>Compare all 16 published assets</small><em>→</em></Link><Link href="/projects/maple-leaf-edu-travel/youtube/daily"><b>Daily</b><small>Read the Jul 13–Aug 9 momentum</small><em>→</em></Link><Link href="/projects/maple-leaf-edu-travel/youtube/retention"><b>Retention</b><small>Separate selection from storytelling</small><em>→</em></Link></article></section>
    <p className="data-footnote">Source: YouTube Studio, captured Aug 10, 2026. Reporting data is complete through Aug 9. Lifetime views are the current public-content row total; 28-day metrics include public, private, unlisted and deleted content under YouTube&apos;s metric definition.</p>
  </YoutubeWorkbenchShell>;
}

