import { MetricCard, YoutubeWorkbenchShell } from "@/components/youtube-workbench-shell";
import { dailyViews, periodSummary } from "@/content/youtube-workbench";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("YouTube Daily — Project 001", "Daily YouTube momentum for Project 001.", "/projects/maple-leaf-edu-travel/youtube/daily");
export default function YoutubeDaily() {
  const maxViews = Math.max(...dailyViews.map((day) => day.views));
  const topDays = [...dailyViews].sort((a, b) => b.views - a.views).slice(0, 3);
  return <YoutubeWorkbenchShell active="Daily" eyebrow="DAILY MOMENTUM" title="See what happened after each publish." copy="A source-backed daily view of the latest complete 28-day YouTube Studio window."><section className="metric-grid three"><MetricCard label="Tracked window" value="28 days" detail={periodSummary.label}/><MetricCard label="28-day views" value={periodSummary.views.toLocaleString()} detail={`${periodSummary.watchHours.toFixed(1)} watch hours`}/><MetricCard label="Publishing cadence" value="10 uploads" detail="Across 5 publishing days"/></section><section className="dashboard-panel daily-chart-panel"><div className="panel-heading"><div><span>DAILY VIEWS</span><h2>Two release waves drove 59% of the period.</h2></div><small>Daily reporting · zeros retained</small></div><div className="daily-bars" role="img" aria-label="Daily views for July 13 through August 9"><div className="chart-grid-lines"/>{dailyViews.map((day) => <i key={day.date} style={{ height: `${Math.max(1, (day.views / maxViews) * 100)}%` }} title={`${day.date}: ${day.views.toLocaleString()} views`} />)}</div><div className="chart-axis"><span>Jul 13</span><span>Jul 23 · 1,544</span><span>Jul 29 · 1,507</span><span>Aug 9</span></div></section><section className="daily-schema">{topDays.map((day, index) => <article key={day.date}><span>0{index + 1} · PEAK DAY</span><h3>{day.date} · {day.views.toLocaleString()} views</h3><p>{((day.views / periodSummary.views) * 100).toFixed(1)}% of all views in the selected 28-day window.</p></article>)}</section><p className="data-footnote">Source: YouTube Studio daily report. Dates with no displayed Studio row are recorded as zero so the 28-day series remains continuous; the series reconciles exactly to 5,195 views.</p></YoutubeWorkbenchShell>;
}

