import Link from "next/link";
import { capabilities } from "@/content/capabilities";
import { project001 } from "@/content/projects";
import { CallToAction } from "@/components/call-to-action";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata("Project 001 — Laicai OS", "An incubation thesis applying the Laicai OS operating model to international K12 education travel.", "/projects/maple-leaf-edu-travel");

export default function Project001() {
  return <>
    <section className="case-hero"><div className="shell"><div className="project-meta"><span>{project001.number}</span><span>{project001.category}</span></div><p className="case-status">{project001.status}</p><h1>{project001.name}</h1><p className="case-positioning">{project001.positioning}</p><div className="actions"><Link className="primary-button inverted" href="/contact">Discuss a project</Link><Link className="text-link light" href="/capabilities">Explore capabilities →</Link></div></div></section>
    <section className="section shell two-col"><div><div className="section-label">THE OPPORTUNITY</div><h2>Build an education brand around authentic learning experiences in China.</h2></div><div className="large-copy"><p>The project explores how a clear brand and operating system can serve international K12 education travel.</p><p>This is an incubation thesis, not a claim of established market performance.</p></div></section>
    <section className="section shell split-list"><div><div className="section-label">THE CHALLENGE</div><h2>Connect the work before scaling it.</h2></div><div><p>Positioning, products, operations, content, outreach and organizational knowledge need to work as one system.</p><p>The project is not simply about creating accounts. It tests whether Laicai OS can build an international brand from zero.</p></div></section>
    <section className="section shell"><div className="section-heading"><div className="section-label">SYSTEM APPLIED</div><h2>All four capabilities, applied to one project.</h2></div><div className="capability-grid">{capabilities.map((item) => <article className="capability-card" key={item.number}><span>{item.number}</span><h3>{item.title}</h3><p>{item.summary}</p></article>)}</div></section>
    <section className="section shell"><div className="section-heading"><div className="section-label">WORKSTREAMS</div><h2>The operating surface.</h2></div><div className="tag-list">{["Brand", "Products", "Operations", "Content", "Distribution", "Partnerships", "Measurement"].map((item) => <span key={item}>{item}</span>)}</div></section>
    <section className="section shell project-workbench-entry"><div><div className="section-label">OPERATING WORKBENCH</div><h2>The project is the product. Data sharpens the next move.</h2><p>YouTube measurement now sits inside the Project 001 operating loop—connected to content decisions, not presented as a standalone analytics business.</p><Link className="primary-button" href="/projects/maple-leaf-edu-travel/youtube">Open YouTube Workbench →</Link></div><div className="workbench-preview"><div className="preview-top"><span>PROJECT 001 · YOUTUBE</span><b>5,306</b><small>verified stage views</small></div><div className="preview-chart"><i/><i/><i/><i/><i/><i/></div><div className="preview-bottom"><span>7 published</span><span>1 detailed snapshot</span></div></div></section>
    <section className="section shell two-col"><div><div className="section-label">LEARNING LOOP</div><h2>Project work should improve the system.</h2></div><div className="large-copy"><p>Decisions, workflows and evidence from Project 001 will be captured as reusable knowledge for later operating cycles.</p><p>The next phase remains planned until its inputs, owners and measurement approach are defined.</p></div></section>
    <CallToAction label="BUILD WITH LAICAI" title="Discuss a project with a real operating challenge." copy="Start with the problem, the users and the evidence you need to create." href="/contact" action="Discuss a project" />
  </>;
}
